<?php

print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
print "<html xmlns=\"http://www.w3.org/1999/xhtml\" id='view_iframe'>\n";
print "	<head>\n";
print "		<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n";
print "		<title></title>\n";
print "		<link href=\"http://i.pastehtml.com/stylesheets/cache/all.css\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\" />\n";
print "		<script type=\"text/javascript\">\n";
print "	window.google_analytics_uacct = \"UA-83599-25\";\n";
print "</script>\n";
print "<script type=\"text/javascript\">\n";
print "  var _gaq = _gaq || [];\n";
print "  _gaq.push(['_setAccount', 'UA-83599-25']);\n";
print "  _gaq.push(['_trackPageview']);\n";
print "\n";
print "  (function() {\n";
print "    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n";
print "    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n";
print "    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n";
print "  })();\n";
print "</script>\n";
print "\n";
print "\n";
print "	<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n";
print "\n";
print "\n";
print "<script src=\"http://i.pastehtml.com/javascripts/cache/all.js\" type=\"text/javascript\"></script>\n";
print "<script src=\"http://i.pastehtml.com/javascripts/rails.js\" type=\"text/javascript\"></script>\n";
print "	</head>\n";
print "	<body>\n";
print "		<div id=\"wrapper\">\n";
print "			<iframe src=\"/raw/bnbo7pvun.html\" frameBorder=\"0\"></iframe>\n";
print "		</div>\n";
print "		<div id=\"controls\">\n";
print "			This page was viewed <b id=\"view_count\">808</b> times and has <a target=\"_top\" href=\"http://pastehtml.com/info/bnbo7pvun.html#disqus_thread\" class=\"disqus_comment_count\" ></a>.\n";
print "			<span class='st_twitter' displayText=''></span>\n";
print "			<span class='st_facebook' displayText=''></span>\n";
print "			<span class='st_googleplus' displayText=''></span>\n";
print "				Sponsored by: <a href='http://search-id.com/k/duke%20rice%20diet'>duke rice diet</a>\n";
print "			<div id=\"hosted_on\">Hosted on</div>\n";
print "			<img alt=\"\" class=\"rounded\" src=\"http://i.pastehtml.com/images/design/iframe/rounded.png\" />\n";
print "			<a href=\"/\" class=\"logo\" target=\"_top\"><img alt=\"PasteHTML.com\" src=\"http://i.pastehtml.com/images/design/iframe/logo.png\" /></a>\n";
print "		</div>\n";
print "\n";
print "		<script type=\"text/javascript\" src=\"http://w.sharethis.com/button/buttons.js\"></script>\n";
print "		<script type=\"text/javascript\">stLight.options({publisher: \"88ec1cfc-eb15-46e5-ae80-479238f71642\"}); </script>\n";
print "		<script type=\"text/javascript\">\n";
print "		    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */\n";
print "		    var disqus_url=\"http://pastehtml.com/info/bnbo7pvun.html\";\n";
print "			var disqus_shortname = 'pastehtmlpastehtml';\n";
print "\n";
print "		    /* * * DON'T EDIT BELOW THIS LINE * * */\n";
print "		    (function () {\n";
print "		        var s = document.createElement('script'); s.async = true;\n";
print "		        s.type = 'text/javascript';\n";
print "		        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';\n";
print "		        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);\n";
print "		    }());\n";
print "		</script>\n";
print "	</body>\n";
print "</html>";

?>